### ISSUE TITLE
Stops after 1 generation

### ISSUE THREAD

**Issue by nlbutts** [neat-python/neat-python#8]
I am trying to come up with a simple system for a regressor. I've taken the XOR example, added my data and changed the fitness_criterion to min:
fitness_criterion     = min

The fitness function is the sum of the squared errors. So I am trying to minimize the errors. The system runs for 1 generation, stops and spits out the best candidate. Which has an huge error. So it doesn't appear to have minimized the error at all. What am I doing wrong?

**Comment by cesargm2015** [comment]
I've seen this happing from time to time. It needs more investigation to fix it.

**Comment by jonnymaserati** [comment]
Getting the same issue... doesn't work with `fitness_criterion = min`

This is the problem in the `population.py` module:

```python
if not self.config.no_fitness_termination:
                # End if the fitness threshold is reached.
                fv = self.fitness_criterion(g.fitness for g in self.population.values())
                if fv >= self.config.fitness_threshold:
                    self.reporters.found_solution(self.config, self.generation, best)
                    break
```
It's not taking account of whether `min` is set and assumes that you're chasing a `max`, so needs changing to something like this:

```python
            if not self.config.no_fitness_termination:
                # End if the fitness threshold is reached.
                fv = self.fitness_criterion(g.fitness for g in self.population.values())
                if (
                    self.config.fitness_criterion == 'min'
                    and fv <= self.config.fitness_threshold
                ):
                    break
                elif (
                    self.config.fitness_criterion == 'max'
                    and fv >= self.config.fitness_threshold
                ):
                    self.reporters.found_solution(self.config, self.generation, best)
                    break
                else:
                    pass
```
